export const USER_DEMANDE_REQUEST = "USER_DEMANDE_REQUEST";
export const USER_DEMANDE_SUCCESS = "USER_DEMANDE_SUCCESS";
export const USER_DEMANDE_FAIL = "USER_DEMANDE_FAIL";

export const USER_ADD_DEMANDE_REQUEST = "USER_ADD_DEMANDE_REQUEST";
export const USER_ADD_DEMANDE_SUCCESS = "USER_ADD_DEMANDE_SUCCESS";
export const USER_ADD_DEMANDE_FAIL = "USER_ADD_DEMANDE_FAIL";

export const USER_UPDATE_DEMANDE_REQUEST = "USER_UPDATE_DEMANDE_REQUEST";
export const USER_UPDATE_DEMANDE_SUCCESS = "USER_UPDATE_DEMANDE_SUCCESS";
export const USER_UPDATE_DEMANDE_FAIL = "USER_UPDATE_DEMANDE_FAIL";
export const USER_UPDATE_DEMANDE_RESET = "USER_UPDATE_DEMANDE_RESET";

export const USER_GET_STATS_REQUEST = "USER_GET_STATS_REQUEST";
export const USER_GET_STATS_SUCCESS = "USER_GET_STATS_SUCCESS";
export const USER_GET_STATS_FAIL = "USER_GET_STATS_FAIL";
export const USER_GET_STATS_RESET = "USER_GET_STATS_RESET";

export const ADMIN_LIST_DEMANDE_REQUEST = "ADMIN_LIST_DEMANDE_REQUEST";
export const ADMIN_LIST_DEMANDE_SUCCESS = "ADMIN_LIST_DEMANDE_SUCCESS";
export const ADMIN_LIST_DEMANDE_FAIL = "ADMIN_LIST_DEMANDE_FAIL";
export const ADMIN_LIST_DEMANDE_RESET = "ADMIN_LIST_DEMANDE_RESET";

export const ADMIN_ACCEPTE_DEMANDE_REQUEST = "ADMIN_ACCEPTE_DEMANDE_REQUEST";
export const ADMIN_ACCEPTE_DEMANDE_SUCCESS = "ADMIN_ACCEPTE_DEMANDE_SUCCESS";
export const ADMIN_ACCEPTE_DEMANDE_FAIL = "ADMIN_ACCEPTE_DEMANDE_FAIL";

export const ADMIN_REFUSE_DEMANDE_REQUEST = "ADMIN_REFUSE_DEMANDE_REQUEST";
export const ADMIN_REFUSE_DEMANDE_SUCCESS = "ADMIN_REFUSE_DEMANDE_SUCCESS";
export const ADMIN_REFUSE_DEMANDE_FAIL = "ADMIN_REFUSE_DEMANDE_FAIL";
